= Projekt Kartenspielen
Projektmitglieder Wagner Moritz, Maximillian Slabschi, Mathias Schablinger, Jakob Michel
1.0.0, {docdate}
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
:experimental:

== Projekt Kartenspielen
== Einführung
Das ITP Projekt kartenspielen handelt von einer Anwendung, auf der man sowohl
Schnapsen lernen kann, als auch online gegen andere Spieler spielen kann.
Genaueres findet man unter folgendem Link: link:asciidoc/Projektauftrag.adoc[Projektauftrag]

Das Projekt wird entwickelt von:

* Wagner Moritz (Projektleiter)
* Slabschi Maximilian
* Schablinger Mathias
* Michel Jakob

== Projektaufbau
* link:asciidoc/[Asciidoc Files]
* link:.github/[Github Files]

== Projektausführung
* Um das Projekt Kartenspielen zum laufen zu bringen, sollten Sie folgende schritte durchführen:
* Als Erstes wechseln Sie in den Ordner Schapsn.
* Danach gilt es das `derbydb-create.sh` script auszuführen.

NOTE: Mit diesem script wird die datenbank erstellt

* Um die Datenbank nun zu starten, führen Sie das `derbydb-start.sh` script aus.
* Um nun eine Verbindung mit der Datenbank herzustellen, navigieren sie rechts auf Database.
* Kopieren Sie den Inhalt aus dem `datasource.txt` und drücken sie anschließend auf das `+` bei Database.
* Im Dropdown sollten sie `Import from Clipboard` finden und dieses anklicken.
* Nun sollten sie nur noch bei Passwort ...
====
app
====
* ... eingeben und dann per click auf `Test connection` sollte ein Popup mit Succeed auftauchen.
* Danach einfach auf `ok` drücken und nun besteht die Verbindung.