= Plichtenheft
Projektmitglieder Wagner Moritz, Maximillian Slabschi, Mathias Schablinger, Jakob Michel
1.0.0, {docdate}
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
:experimental:

== Ausgangssituation
Wir sind ein 4 Mann (Schüler) Team. Wir befinden uns in Leonding, das ist im Zentralraum von Oberösterreich.

== Istzustand
Zurzeit gibt es viel zu wenige Personen die Schnapsen verstehen.
Die, die wissen wie das Spiel funktioniert, können sich aufgrund von mangelnder Spieler nicht großartig verbessern.

== Problemstellung

* Personen können dieses Spiel nicht lernen.
* Spieler können sich nicht großartig verbessern.
* Spieler können sich nicht messen.

== Sollzustand
Eine Anwendung ist zu programmieren, wo jeder die Regeln von 2 P-Schnaspen, 3 P-Schnapsen und 4 P-Schnapsen
lernen kann. Die Leute, die es schon beherrschen, können Online gegen andere Spieler spielen und sich mit ihnen messen.

== Ziel
Leute können leichter Schnapsen lernen und sich verbessern, aber vor allem sollen
sie Spaß am spielen haben.