= Projektauftag 22/23 / 3AHITM / ITP
Wagner Moritz, Maximillian Slabschi, Mathias Schablinger, Jakob Michel
1.0.0, {docdate}: ITP
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
:experimental:

== Projektbezeichnung
App zum Schnapsen lernen.

== Projekthintergrund
Eine online Spiel, welches einem ermöglicht Schnapsen zu spielen und zu lernen.

== Projektziele
* Schnapsen beizubringen
* Ermöglichen online zu schnapsen und zu auszuprobieren
* Man soll Spaß am Spiel haben

== Projektbeschreibung



Es soll eine App programmiert werden, wo man 2P-Schnaspen, 3P-Schnapsen und 4P-Schnapsen.
Es sollen alle Spielmodi vorhanden sein.

Man soll online und gegen den Computer spielen können. Damit man aber überhaupt spielen kann,
muss man einen Account anlegen. Es wird auch hin und wieder eine Werbung geschaltet.

Die App soll Benutzer- und anfängerfreundlich sein.

Anwendung, auf der man Schnapsen lernen und spielen kann.

=== Use-Case-Diagramm
[plantuml,demo-cld,png]
----
@startuml
left to right direction
actor spieler
rectangle Kartenspiel {
    usecase "lernen von Doppeldeutschen Karten" as karten
    usecase "lernen vom Spiel "Schnapsen"" as lernen
    usecase "Spielen mit anderen Spielern" as spielen
}
spieler --> karten
spieler --> lernen
spieler --> spielen
@enduml
----

== Projektphasen / Meilensteine
|===
|*Phase* |*Meilenstein/Ergebnis* |*Solltermin*
|*Projektinitiierung* |Zusage zur Durchführung des Projektes |21.11.2022
|*Projektplanung* |Projektplan |unbekannt
|*Projektdurchführung* |Wireframe der App,
Kennzeichnung der Grundstruktur |unbekannt
| |Mockup der App,
Veranschaulichung des Designs|unbekannt
| |Prototyp der App,
funktionierende Version des Projektes|unbekannt
| |Fertige App |unbekannt
|*Projektevaluierung* |Projektbericht |unbekannt
|===

== Projektstart
21.11.2022

== Projektende
unbekannt

== Projektressourcen
|===
|*Infrastruktur* |*Menge* |*Euro & Einheit* |*Betrag*
|Server |1 |4,99 €/Monat |4,99 €
|===
|===
|*Personal* |*Menge*
|Projektleiter |1
|Programmierer |4
|===